//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EternalCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EternalCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Borrowed Violence (Set5 #149)
        ///1 Endure (Set5 #75)
        ///1 Melt Down (Set5 #1)
        ///1 Steely Resolve (Set5 #112)
        ///1 Unearth the Past (Set5 #38)
        ///1 Araktodon Egg (Set5 #41)
        ///1 Astromancer&apos;s Compass (Set5 #251)
        ///1 Be Gone (Set5 #39)
        ///1 Cabal Scavenger (Set5 #150)
        ///1 Crystal Dirk (Set5 #113)
        ///1 Mischief Yeti (Set5 #115)
        ///1 Oni Samurai (Set5 #78)
        ///1 Research Assistant (Set5 #4)
        ///1 Scorpion (Set5 #42)
        ///1 Softfoot Burglar (Set5 #5)
        ///1 Unmoored Valkyrie (Set5 #80)
        ///1 Bannerman (Set5 #252)
        ///1 Barrel Through (Set5 #82)
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Defiance_Common {
            get {
                return ResourceManager.GetString("Defiance_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Snowdrift Delver (Set5 #124)
        ///1 Tavia, Lethrai Raidleader (Set5 #164)
        ///1 Torgov&apos;s Trading Post (Set5 #203)
        ///1 Kemmo, Ijin&apos;s Apprentice (Set5 #89)
        ///1 Nika, the Freescaler (Set5 #17)
        ///1 Phoenix Stone (Set5 #18)
        ///1 Bladerang (Set5 #21)
        ///1 Clutch of Talons (Set5 #133)
        ///1 Cykalis, the Burning Sand (Set5 #57)
        ///1 Darya, Warrior Poet (Set5 #186)
        ///1 Dumping Ground (Set5 #169)
        ///1 Flamebrewer (Set5 #20)
        ///1 Governor Sahin (Set5 #171)
        ///1 Ijin&apos;s Workshop (Set5 #200)
        ///1 Regent&apos;s Tomb (Set5 #213)
        ///1 The Praxis Arcanum (S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Defiance_Legendary {
            get {
                return ResourceManager.GetString("Defiance_Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Star-Reader Severin (Set5 #312)
        ///1 Cursed Prophet Deleph (Set5 #314)
        ///1 Milos, Unwavering Idealist (Set5 #313)
        ///1 Justa, Regglar Jotun (Set5 #311).
        /// </summary>
        internal static string Defiance_Promo {
            get {
                return ResourceManager.GetString("Defiance_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Adjudicator&apos;s Gavel (Set5 #76)
        ///1 Auralian Cargo (Set5 #232)
        ///1 Crested Runt (Set5 #40)
        ///1 Ixtun Cargo (Set5 #227)
        ///1 Jennev Cargo (Set5 #242)
        ///1 Kerendon Cargo (Set5 #247)
        ///1 Savagery (Set5 #117)
        ///1 Weary Spiteling (Set5 #155)
        ///1 Winchest Cargo (Set5 #237)
        ///1 Bazaar Trickster (Set5 #43)
        ///1 Golem Press (Set5 #85)
        ///1 Highland Sharpshooter (Set5 #197)
        ///1 Hojan, Crownbreaker (Set5 #86)
        ///1 Mournful Deathcap (Set5 #161)
        ///1 Notorious Scoundrel (Set5 #9)
        ///1 Stormtamer Operative (Set5 #118)
        ///1 Vapor Hut (Set5 #50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Defiance_Rare {
            get {
                return ResourceManager.GetString("Defiance_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Bottoms Up (Set5 #2)
        ///1 Cautious Traveler (Set5 #3)
        ///1 Defiance (Set5 #77)
        ///1 Direwood Slasher (Set5 #151)
        ///1 Frostwave (Set5 #114)
        ///1 Lethrai Lobotomy (Set5 #152)
        ///1 Pitfall Trap (Set5 #116)
        ///1 Rat Cage (Set5 #153)
        ///1 Secret Passage (Set5 #154)
        ///1 Svetya&apos;s Bravery (Set5 #79)
        ///1 Urn of Choking Embers (Set5 #6)
        ///1 Axe Sharpener (Set5 #81)
        ///1 Blood Quill (Set5 #156)
        ///1 Chancellor&apos;s Horn (Set5 #83)
        ///1 Dissociate (Set5 #44)
        ///1 Firemane Lioness (Set5 #8)
        ///1 Heirloom Seeker (Set5 #158)
        ///1 Locust (Set5 #45)
        ///1 O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Defiance_Uncommon {
            get {
                return ResourceManager.GetString("Defiance_Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Helpful Doorbot (Set3 #2)
        ///1 Affliction (Set3 #202)
        ///1 Ancient Bauble (Set3 #54)
        ///1 Farplace Finder (Set3 #153)
        ///1 Grenamender (Set3 #204)
        ///1 Iceberg Frontrunner (Set3 #3)
        ///1 Jump Kick (Set3 #154)
        ///1 Lucky Prospector (Set3 #57)
        ///1 Scrap Hound (Set3 #6)
        ///1 Sinister Opportunist (Set3 #157)
        ///1 Steady Marshal (Set3 #105)
        ///1 Trusty Revolver (Set3 #206)
        ///1 Copperhall Porter (Set3 #108)
        ///1 Cryptic Etchings (Set3 #62)
        ///1 Disjunction (Set3 #63)
        ///1 Flashy Duelist (Set3 #213)
        ///1 Into the Furnace (Set3 #9)
        ///1 Nocturn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DuskRoad_Common {
            get {
                return ResourceManager.GetString("DuskRoad_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Azurite Prixis (Set3 #52)
        ///1 Kennelmaster (Set3 #5)
        ///1 Tax Collector (Set3 #113)
        ///1 Darkclaw Ravager (Set3 #221)
        ///1 Stella, the Shotcaller (Set3 #120)
        ///1 Sunken Tower (Set3 #175)
        ///1 Crownwatch Traitor (Set3 #265)
        ///1 Kaleb, Reborn (Set3 #255)
        ///1 Kyojun, Grand Shugo (Set3 #31)
        ///1 Lastlight Druid (Set3 #172)
        ///1 Lumen Reclaimer (Set3 #80)
        ///1 Rindra, the Duskblade (Set3 #277)
        ///1 Thudrock, Arctic Artisan (Set3 #186)
        ///1 Vicious Highwayman (Set3 #275)
        ///1 Alu, Death-Dreamer (Set3 #192)
        ///1 Amilli, Cloudmarshal (Set [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DuskRoad_Legendary {
            get {
                return ResourceManager.GetString("DuskRoad_Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Brenn, Chronicler of Ages (Set3 #303)
        ///1 Bloodscent Avisaur (Set3 #301)
        ///1 Svetya, Orene of Kosul (Set3 #304)
        ///1 Dizo, Cabal Chairman (Set3 #302).
        /// </summary>
        internal static string DuskRoad_Promo {
            get {
                return ResourceManager.GetString("DuskRoad_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hesitate (Set3 #56)
        ///1 Powderglider (Set3 #155)
        ///1 Snow Pelting (Set3 #158)
        ///1 Stonescar Sneak (Set3 #205)
        ///1 Twilight Hunt (Set3 #59)
        ///1 Whetstone (Set3 #107)
        ///1 Accelerated Impact (Set3 #60)
        ///1 Ask for Directions (Set3 #61)
        ///1 Combustion Cell (Set3 #7)
        ///1 Corrupt (Set3 #210)
        ///1 Curfew Enforcement (Set3 #110)
        ///1 Darkveil Agent (Set3 #160)
        ///1 Dreamsnatcher (Set3 #212)
        ///1 Hideout Pistol (Set3 #215)
        ///1 Iceberg Mason (Set3 #163)
        ///1 Miner&apos;s Musket (Set3 #10)
        ///1 Miris Nightshade (Set3 #217)
        ///1 Yeti Sage (Set3  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DuskRoad_Rare {
            get {
                return ResourceManager.GetString("DuskRoad_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Amaran Shoveler (Set3 #53)
        ///1 Arachnophobia (Set3 #203)
        ///1 Eilyn&apos;s Intervention (Set3 #152)
        ///1 Family Charter (Set3 #280)
        ///1 Gloaming Wisp (Set3 #55)
        ///1 Humble Instructor (Set3 #103)
        ///1 Kaleb&apos;s Intervention (Set3 #4)
        ///1 Rolant&apos;s Intervention (Set3 #104)
        ///1 Savage Skybrood (Set3 #156)
        ///1 Talir&apos;s Intervention (Set3 #58)
        ///1 Vara&apos;s Intervention (Set3 #207)
        ///1 Wisplight (Set3 #208)
        ///1 Battlefield Scavenger (Set3 #209)
        ///1 Cowardice (Set3 #211)
        ///1 Crackshot Fugitive (Set3 #109)
        ///1 Darkbolt (Set3 #159)
        ///1 Disasse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DuskRoad_Uncommon {
            get {
                return ResourceManager.GetString("DuskRoad_Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Blood Beetle (Set1 #260)
        ///1 Combust (Set1 #392)
        ///1 Dark Return (Set1 #250)
        ///1 Detain (Set1 #133)
        ///1 Direfang Spider (Set1 #256)
        ///1 District Infantry (Set1 #134)
        ///1 Finest Hour (Set1 #130)
        ///1 Grenadin Drone (Set1 #5)
        ///1 Heavy Axe (Set1 #4)
        ///1 Humbug (Set1 #72)
        ///1 Initiate of the Sands (Set1 #74)
        ///1 Levitate (Set1 #190)
        ///1 Oni Ronin (Set1 #13)
        ///1 Ornamental Daggers (Set1 #69)
        ///1 Pilfer (Set1 #254)
        ///1 Predator&apos;s Instinct (Set1 #75)
        ///1 Ruin (Set1 #15)
        ///1 Sabotage (Set1 #252)
        ///1 Safe Return (Set1 #330)
        ///1 Sanc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyThrone_Common {
            get {
                return ResourceManager.GetString("EmptyThrone_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Call the Ancients (Set1 #350)
        ///1 Light the Fuse (Set1 #6)
        ///1 Crown of Possibilities (Set1 #355)
        ///1 Feln Cauldron (Set1 #380)
        ///1 Ijin, Imperial Armorer (Set1 #326)
        ///1 Knight-Chancellor Siraf (Set1 #335)
        ///1 Midnight Gale (Set1 #378)
        ///1 Bandit Queen (Set1 #389)
        ///1 Navani, Warsinger (Set1 #323)
        ///1 Sandstorm Titan (Set1 #99)
        ///1 Statuary Maiden (Set1 #387)
        ///1 The Great Parliament (Set1 #338)
        ///1 Treasury Gate (Set1 #164)
        ///1 Cirso, the Great Glutton (Set1 #362)
        ///1 Deepforged Plate (Set1 #317)
        ///1 Idol of Destran ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyThrone_Legendary {
            get {
                return ResourceManager.GetString("EmptyThrone_Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Wump, Party Starter (Set1 #511)
        ///1 Alpine Tracker (Set1 #522)
        ///1 Azindel, the Wayfinder (Set1 #518)
        ///1 Rilgon, Hooru Operative (Set1 #519)
        ///1 Arcanum Monitor (Set1 #520)
        ///1 Oathbreaker (Set1 #521).
        /// </summary>
        internal static string EmptyThrone_Promo {
            get {
                return ResourceManager.GetString("EmptyThrone_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Trail Stories (Set1 #188)
        ///1 Fearless Nomad (Set1 #311)
        ///1 Pyroknight (Set1 #16)
        ///1 Accelerated Evolution (Set1 #351)
        ///1 Argenport Instigator (Set1 #268)
        ///1 Brazen Daredevil (Set1 #19)
        ///1 Champion of Glory (Set1 #314)
        ///1 Charchain Flail (Set1 #3)
        ///1 Cloudsnake Saddle (Set1 #199)
        ///1 Copper Conduit (Set1 #66)
        ///1 Eager Owlet (Set1 #144)
        ///1 Ephemeral Wisp (Set1 #84)
        ///1 Frontier Jito (Set1 #9)
        ///1 Grim Stranger (Set1 #372)
        ///1 Hair-Trigger Stranger (Set1 #253)
        ///1 Paladin Oathbook (Set1 #140)
        ///1 Rakano Artisan (S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyThrone_Rare {
            get {
                return ResourceManager.GetString("EmptyThrone_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Sand Warrior (Set1 #64)
        ///1 Spiked Helm (Set1 #406)
        ///1 Blind Storyteller (Set1 #192)
        ///1 Elder&apos;s Feather (Set1 #128)
        ///1 Excavate (Set1 #71)
        ///1 Ghostform (Set1 #258)
        ///1 Infinite Hourglass (Set1 #67)
        ///1 Knifejack (Set1 #257)
        ///1 Permafrost (Set1 #193)
        ///1 Ruthless Stranger (Set1 #11)
        ///1 Silence (Set0 #9)
        ///1 Slow (Set1 #70)
        ///1 Slumbering Stone (Set1 #255)
        ///1 Suffocate (Set1 #251)
        ///1 Tinker Apprentice (Set1 #131)
        ///1 Twilight Raptor (Set1 #379)
        ///1 Unstable Form (Set1 #189)
        ///1 Warhelm (Set1 #14)
        ///1 Annihilate (Set1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyThrone_Uncommon {
            get {
                return ResourceManager.GetString("EmptyThrone_Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Bloodcall Invocation (Set2 #203)
        ///1 Cloudsnake Hatchling (Set2 #103)
        ///1 Envelop (Set2 #36)
        ///1 Excavation Assistant (Set2 #37)
        ///1 Fallen Oni (Set2 #138)
        ///1 Forge Wolf (Set2 #2)
        ///1 Minotaur Oathkeeper (Set2 #70)
        ///1 Pummel (Set2 #6)
        ///1 Swear Vengeance (Set2 #140)
        ///1 Tock Tick (Set2 #141)
        ///1 Weather the Storm (Set2 #106)
        ///1 Young Gun (Set2 #3)
        ///1 Argenport Stranger (Set2 #246)
        ///1 Auric Bully (Set2 #232)
        ///1 Blinkwolf (Set2 #7)
        ///1 Bring Down (Set2 #217)
        ///1 Cabal Slasher (Set2 #147)
        ///1 Copperhall Herald (Set2 #7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OmensOfThePast_Common {
            get {
                return ResourceManager.GetString("OmensOfThePast_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Wandering Wisp (Set2 #38)
        ///1 Kothon, the Far-Watcher (Set2 #218)
        ///1 Ayan, the Abductor (Set2 #204)
        ///1 Means to an End (Set2 #154)
        ///1 Mind Link (Set2 #119)
        ///1 Vadius, Clan Father (Set2 #191)
        ///1 Bartholo, the Seducer (Set2 #234)
        ///1 Diogo Málaga (Set2 #179)
        ///1 Mask of Torment (Set2 #212)
        ///1 Watcher of the Big Ones (Set2 #130)
        ///1 Inquisitor Makto (Set2 #242)
        ///1 Obrak, the Feaster (Set2 #164)
        ///1 Pearlescent Drake (Set2 #127)
        ///1 Bad News (Set2 #30)
        ///1 Flamestoker (Set2 #32)
        ///1 Heart of the Vault (Set2 #183)
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OmensOfThePast_Legendary {
            get {
                return ResourceManager.GetString("OmensOfThePast_Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Colony Matron (Set2 #255)
        ///1 Veteran Mercenary (Set2 #252)
        ///1 Kosul Brigade (Set2 #254)
        ///1 Tesya, Omen Shaper (Set2 #256).
        /// </summary>
        internal static string OmensOfThePast_Promo {
            get {
                return ResourceManager.GetString("OmensOfThePast_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 On the Hunt (Set2 #5)
        ///1 Auric Vigilante (Set2 #233)
        ///1 Champion of Fury (Set2 #187)
        ///1 Evelina, Valley Searcher (Set2 #48)
        ///1 Forgotten Find (Set2 #40)
        ///1 Maelstrom Bell (Set2 #109)
        ///1 Mating Call (Set2 #110)
        ///1 Reunite (Set2 #249)
        ///1 Banish (Set2 #207)
        ///1 Bloodletter (Set2 #235)
        ///1 Cat Burglar (Set2 #148)
        ///1 Champion of Impulse (Set2 #173)
        ///1 Cloudsnake Harrier (Set2 #114)
        ///1 Shepherd&apos;s Horn (Set2 #49)
        ///1 Spirit Guide (Set2 #83)
        ///1 Stonescar Excavator (Set2 #14)
        ///1 Beckoning Lumen (Set2 #59)
        ///1 Calderan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OmensOfThePast_Rare {
            get {
                return ResourceManager.GetString("OmensOfThePast_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Alluring Ember (Set2 #172)
        ///1 Brash Shorthorn (Set2 #137)
        ///1 Crownwatch Squire (Set2 #69)
        ///1 Cult Aspirant (Set2 #35)
        ///1 Firemane Cub (Set2 #1)
        ///1 Hearty Stranger (Set2 #104)
        ///1 Hidden Shiv (Set2 #4)
        ///1 Jack&apos;s Knife (Set2 #139)
        ///1 Snowcrust Yeti (Set2 #105)
        ///1 Blistersting Wasp (Set2 #202)
        ///1 Cloudsnake Breeder (Set2 #107)
        ///1 Kaleb&apos;s Choice (Set2 #188)
        ///1 Noble Firemane (Set2 #174)
        ///1 Oasis Seeker (Set2 #41)
        ///1 Piercing Grief (Set2 #143)
        ///1 Rockslide (Set2 #189)
        ///1 Sandstorm (Set2 #43)
        ///1 Scare (Set2 #144 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OmensOfThePast_Uncommon {
            get {
                return ResourceManager.GetString("OmensOfThePast_Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Drifter (Set4 #2)
        ///1 Gift of Battle (Set4 #146)
        ///1 Harbinger&apos;s Bite (Set4 #194)
        ///1 Jibbering Jackal (Set4 #52)
        ///1 Journey Guide (Set4 #53)
        ///1 Light &apos;em Up (Set4 #4)
        ///1 Lingering Influence (Set4 #100)
        ///1 Lock Horns (Set4 #207)
        ///1 Meditation (Set4 #54)
        ///1 Peacekeeper&apos;s Helm (Set4 #101)
        ///1 Rambot (Set4 #7)
        ///1 Sharpened Reflex (Set4 #102)
        ///1 Shiver (Set4 #148)
        ///1 Snowrager (Set4 #149)
        ///1 Spire Spellsword (Set4 #103)
        ///1 Spitefeeder (Set4 #197)
        ///1 Training Ground (Set4 #59)
        ///1 Afterimage (Set4 #212)
        ///1 Arcane D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheFallOfArgenport_Common {
            get {
                return ResourceManager.GetString("TheFallOfArgenport_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Time Flies (Set4 #58)
        ///1 Blackhall Warleader (Set4 #201)
        ///1 Ironfist Chancellor (Set4 #108)
        ///1 Lida&apos;s Apprentice (Set4 #158)
        ///1 Scale Seeker (Set4 #15)
        ///1 Teacher of Humility (Set4 #67)
        ///1 Copperhall Bracers (Set4 #115)
        ///1 Horde Plunderer (Set4 #168)
        ///1 Void Drummer (Set4 #222)
        ///1 Wingbrewer (Set4 #223)
        ///1 Breeze Dancer (Set4 #174)
        ///1 Dramatist&apos;s Mask (Set4 #31)
        ///1 Geomar, the Steel Tempest (Set4 #128)
        ///1 Gnash, Pridemaster (Set4 #79)
        ///1 Jawbone Greatsword (Set4 #33)
        ///1 Lethrai Provocateur (Set4 #228)
        ///1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheFallOfArgenport_Legendary {
            get {
                return ResourceManager.GetString("TheFallOfArgenport_Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Wyatt, Junk Collector (Set4 #306)
        ///1 Genetrix Irel IV (Set4 #307)
        ///1 Yushkov, the Usurper (Set4 #310)
        ///1 Tamarys, the Geomancer (Set4 #308)
        ///1 Caiphus, Wandering King (Set4 #309).
        /// </summary>
        internal static string TheFallOfArgenport_Promo {
            get {
                return ResourceManager.GetString("TheFallOfArgenport_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Alessi, Combrei Archmage (Set4 #248)
        ///1 Longbarrel (Set4 #5)
        ///1 Pathlighter (Set4 #55)
        ///1 Randori (Set4 #56)
        ///1 Sandstorm Scarf (Set4 #50)
        ///1 Amaran Armadillo (Set4 #60)
        ///1 Bar the Gates (Set4 #105)
        ///1 Barricade (Set4 #106)
        ///1 Bulletshaper (Set4 #244)
        ///1 Derry Cathain, Ripclaw Rider (Set4 #251)
        ///1 Factory Quota (Set4 #17)
        ///1 Fearbinder (Set4 #203)
        ///1 Fenris Nightshade (Set4 #204)
        ///1 Flamebelcher (Set4 #10)
        ///1 Honored Skyguard (Set4 #155)
        ///1 Quicktrigger Outlaw (Set4 #13)
        ///1 Recon Tower (Set4 #275)
        ///1 Rilg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheFallOfArgenport_Rare {
            get {
                return ResourceManager.GetString("TheFallOfArgenport_Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Harmless Question (Set4 #98)
        ///1 Entrancer (Set4 #51)
        ///1 Feed the Flames (Set4 #3)
        ///1 Feral Spiteling (Set4 #205)
        ///1 Horrifying Helm (Set4 #195)
        ///1 Ironfist Faithful (Set4 #99)
        ///1 Mindfire (Set4 #6)
        ///1 Savage Denial (Set4 #147)
        ///1 Sewer Sludge (Set4 #196)
        ///1 Staff of Speed (Set4 #57)
        ///1 Substitute (Set4 #150)
        ///1 Xenan Lifespeaker (Set4 #198)
        ///1 Abduct (Set4 #199)
        ///1 Ankle Cutter (Set4 #8)
        ///1 Campfire Watchman (Set4 #151)
        ///1 Consuming Flames (Set4 #9)
        ///1 Cull the Deck (Set4 #202)
        ///1 Dusk Raider (Set4 #153)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheFallOfArgenport_Uncommon {
            get {
                return ResourceManager.GetString("TheFallOfArgenport_Uncommon", resourceCulture);
            }
        }
    }
}
